//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Exchanges = new HashSet<Exchange>();
            this.Portfolios = new HashSet<Portfolio>();
            this.Parties = new HashSet<Party>();
            this.Security_Detail = new HashSet<Security_Detail>();
            this.Security_Detail1 = new HashSet<Security_Detail>();
        }
    
        public string Country_Code { get; set; }
        public string Country_Name { get; set; }
        public int Weekend_Start { get; set; }
        public int Weekend_End { get; set; }
        public string ISO_Country_Code { get; set; }
        public string BB_Country_Code { get; set; }
        public Nullable<bool> system_locked { get; set; }
    
        public virtual ICollection<Exchange> Exchanges { get; set; }
        public virtual ICollection<Portfolio> Portfolios { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
        public virtual ICollection<Security_Detail> Security_Detail { get; set; }
        public virtual ICollection<Security_Detail> Security_Detail1 { get; set; }
    }
}
