//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metope.DAL
{
    using System;
    using Metope.DAL.MyMetaData;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    [MetadataType(typeof(ForexForecastModelMetaData))]
     
    public partial class Forex_Forecast : IValidatableObject
    {
        public decimal Entity_ID { get; set; }
        public decimal Security_ID { get; set; }
        public string Month_Year { get; set; }
        public Nullable<decimal> Forecast_Rate { get; set; }
        public System.DateTime Last_Update_Date { get; set; }
        public string Last_Update_User { get; set; }
    
        public virtual Security_Detail Security_Detail { get; set; }
        public virtual User User { get; set; } 
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {   // 
            int month = int.Parse(Month_Year.Substring(0,2));
            if (month > 12 ) 
                    yield return new ValidationResult("Invalid month entered");

            int yyyy = int.Parse(Month_Year.Substring(2, 4)); 
            if (Math.Abs(yyyy - DateTime.Now.Year) > 90)
                yield return new ValidationResult("Invalid year entered. Out of range!");
        }
    }
}
