//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metope.DAL
{
    using Metope.DAL.MyMetaData;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ForexForecastModelMetaData))]
    public partial class Forex_Forecast
    {
        public decimal Entity_ID { get; set; }
        public decimal Security_ID { get; set; }
        public string Month_Year { get; set; }
        public Nullable<decimal> Forecast_Rate { get; set; }
        public System.DateTime Last_Update_Date { get; set; }
        public string Last_Update_User { get; set; }
    
        public virtual Security_Detail Security_Detail { get; set; }
        public virtual User User { get; set; }
    }
}
