//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    using MetopeMVCApp.Models.MyMetaData;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(PartyModelMetaData))]
    
    public partial class Party
    {
        public decimal Entity_ID { get; set; }
        public string Party_Code { get; set; }
        public string Party_Name { get; set; }
        public string Party_Type { get; set; }
        public Nullable<System.DateTime> Financial_Year_End { get; set; }
        public string Country_Code { get; set; }
        public Nullable<bool> System_Locked { get; set; }
        public string SWIFT_ID { get; set; }
        public string BIC_Code { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
