//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metope.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portfolio_Valuation_History
    {
        public string Portfolio_Code { get; set; }
        public decimal Entity_ID { get; set; }
        public Nullable<decimal> Net_Asset_Value { get; set; }
        public Nullable<decimal> Gross_Asset_Value { get; set; }
        public Nullable<decimal> Total_Investments { get; set; }
        public Nullable<decimal> Total_Cash { get; set; }
        public Nullable<decimal> Liabilities { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<decimal> Total_Cost { get; set; }
        public Nullable<decimal> NAV_Excl_Fees { get; set; }
        public string Last_Update_User { get; set; }
        public Nullable<System.DateTime> Last_Update_Date { get; set; }
        public System.DateTime Record_Date { get; set; }
        public Nullable<decimal> Session_ID { get; set; }
        public Nullable<System.DateTime> Hist_Last_Update_Date { get; set; }
        public string Hist_Last_Update_User { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Portfolio Portfolio { get; set; }
        public virtual User User { get; set; }
    }
}
