//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metope.DAL
{
    using System;
    using System.Collections.Generic;

    using Metope.DAL.MyMetaData;
    using System.ComponentModel.DataAnnotations;
    [MetadataType(typeof(PositionSODModelMetatData))]
    public partial class Position_SOD
    {
        public decimal Entity_ID { get; set; }
        public string Portfolio_Code { get; set; }
        public decimal Security_ID { get; set; }
        public string Long_Short_Indicator { get; set; }
        public System.DateTime Position_Date { get; set; }
        public Nullable<decimal> Dealt_Quantity { get; set; }
        public Nullable<decimal> Unsettled_Quantity { get; set; }
        public Nullable<decimal> Settled_Quantity { get; set; }
        public Nullable<decimal> Dealt_AllIn_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Unsettled_AllIn_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Settled_AllIn_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Dealt_AllIn_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Unsettled_AllIn_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Settled_AllIn_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Dealt_Clean_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Unsettled_Clean_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Settled_Clean_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Dealt_Clean_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Unsettled_Clean_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Settled_Clean_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Dealt_Income_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Unsettled_Income_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Settled_Income_Mkt_Value_PriceCur { get; set; }
        public Nullable<decimal> Dealt_Income_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Unsettled_Income_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Settled_Income_Mkt_Value_BaseCur { get; set; }
        public Nullable<decimal> Exposure_BaseCur { get; set; }
        public Nullable<decimal> Exposure_PriceCur { get; set; }
        public Nullable<decimal> Average_Unit_Cost_BaseCur { get; set; }
        public Nullable<decimal> Average_Unit_Cost_PriceCur { get; set; }
        public Nullable<decimal> Pledged_Quantity { get; set; }
        public Nullable<decimal> Segregated_Quantity { get; set; }
        public Nullable<decimal> Model_Percent { get; set; }
        public System.DateTime Last_Update_Date { get; set; }
        public string Last_Update_User { get; set; }
        public Nullable<decimal> Unsettled_Expenses_BaseCur { get; set; }
        public Nullable<decimal> Unsettled_Expenses_PriceCur { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Portfolio Portfolio { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Security_Detail Security_Detail { get; set; }
    }
}
