//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_Dividend_Split
    {
        public decimal Dividend_Annual_Number { get; set; }
        public decimal Dividend_Split { get; set; }
        public decimal Entity_ID { get; set; }
        public decimal Security_ID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Security_Detail Security_Detail { get; set; }
    }
}
