//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metope.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Portfolios = new HashSet<Portfolio>();
            this.Security_Price = new HashSet<Security_Price>();
            this.Security_Price_History = new HashSet<Security_Price_History>();
            this.Security_Dividend_Detail = new HashSet<Security_Dividend_Detail>();
            this.Security_Analytics = new HashSet<Security_Analytics>();
            this.Portfolio_Valuation = new HashSet<Portfolio_Valuation>();
            this.Portfolio_Valuation_History = new HashSet<Portfolio_Valuation_History>();
            this.Order_Detail = new HashSet<Order_Detail>();
            this.Order_Detail1 = new HashSet<Order_Detail>();
            this.Order_Detail2 = new HashSet<Order_Detail>();
            this.Order_Detail3 = new HashSet<Order_Detail>();
            this.Order_Detail4 = new HashSet<Order_Detail>();
            this.Order_Detail5 = new HashSet<Order_Detail>();
            this.Position_SOD = new HashSet<Position_SOD>();
            this.Position_SOD1 = new HashSet<Position_SOD>();
            this.Cash_Transactions = new HashSet<Cash_Transactions>();
            this.Cash_Transactions1 = new HashSet<Cash_Transactions>();
            this.Security_Performance = new HashSet<Security_Performance>();
            this.Security_Performance_History = new HashSet<Security_Performance_History>();
            this.Order_Allocation = new HashSet<Order_Allocation>();
            this.Security_Attribution = new HashSet<Security_Attribution>();
        }
    
        public decimal Entity_ID { get; set; }
        public string User_Code { get; set; }
        public string User_Name { get; set; }
        public string User_Initial { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_Address { get; set; }
        public string Active_Indicator { get; set; }
        public string Export_Folder { get; set; }
        public string User_Type { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Password_Expire_Date { get; set; }
        public string Lock_Indicator { get; set; }
        public Nullable<int> Login_Fail_Count { get; set; }
        public Nullable<System.DateTime> Login_Fail_Time { get; set; }
        public Nullable<System.DateTime> Last_Login_Time { get; set; }
        public bool System_Locked { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<Portfolio> Portfolios { get; set; }
        public virtual ICollection<Security_Price> Security_Price { get; set; }
        public virtual ICollection<Security_Price_History> Security_Price_History { get; set; }
        public virtual ICollection<Security_Dividend_Detail> Security_Dividend_Detail { get; set; }
        public virtual ICollection<Security_Analytics> Security_Analytics { get; set; }
        public virtual ICollection<Portfolio_Valuation> Portfolio_Valuation { get; set; }
        public virtual ICollection<Portfolio_Valuation_History> Portfolio_Valuation_History { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail1 { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail2 { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail3 { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail4 { get; set; }
        public virtual ICollection<Order_Detail> Order_Detail5 { get; set; }
        public virtual ICollection<Position_SOD> Position_SOD { get; set; }
        public virtual ICollection<Position_SOD> Position_SOD1 { get; set; }
        public virtual ICollection<Cash_Transactions> Cash_Transactions { get; set; }
        public virtual ICollection<Cash_Transactions> Cash_Transactions1 { get; set; }
        public virtual ICollection<Security_Performance> Security_Performance { get; set; }
        public virtual ICollection<Security_Performance_History> Security_Performance_History { get; set; }
        public virtual ICollection<Order_Allocation> Order_Allocation { get; set; }
        public virtual ICollection<Security_Attribution> Security_Attribution { get; set; }
    }
}
