//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code_Miscellaneous
    {
        public decimal Entity_ID { get; set; }
        public string MisCode_Type { get; set; }
        public string MisCode { get; set; }
        public string MisCode_Description { get; set; }
        public string MisCode_Exception1 { get; set; }
        public string MisCode_Exception2 { get; set; }
        public Nullable<bool> System_Locked { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
