//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Currency_Pair = new HashSet<Currency_Pair>();
            this.Currency_Pair1 = new HashSet<Currency_Pair>();
            this.Portfolios = new HashSet<Portfolio>();
            this.Portfolios1 = new HashSet<Portfolio>();
            this.Portfolios2 = new HashSet<Portfolio>();
            this.Security_Price = new HashSet<Security_Price>();
            this.Security_Price_History = new HashSet<Security_Price_History>();
            this.Security_Detail2 = new HashSet<Security_Detail>();
            this.Security_Detail3 = new HashSet<Security_Detail>();
            this.Security_Detail4 = new HashSet<Security_Detail>();
            this.Security_Detail5 = new HashSet<Security_Detail>();
        }
    
        public string Currency_Code { get; set; }
        public string ISO_Currency_Code { get; set; }
        public string Currency_Symbol { get; set; }
        public string Currency_Name { get; set; }
        public bool System_Locked { get; set; }
        public Nullable<decimal> Currency_Security_ID { get; set; }
        public Nullable<decimal> Synthetic_Security_ID { get; set; }
    
        public virtual ICollection<Currency_Pair> Currency_Pair { get; set; }
        public virtual ICollection<Currency_Pair> Currency_Pair1 { get; set; }
        public virtual ICollection<Portfolio> Portfolios { get; set; }
        public virtual ICollection<Portfolio> Portfolios1 { get; set; }
        public virtual ICollection<Portfolio> Portfolios2 { get; set; }
        public virtual ICollection<Security_Price> Security_Price { get; set; }
        public virtual ICollection<Security_Price_History> Security_Price_History { get; set; }
        public virtual Security_Detail Security_Detail { get; set; }
        public virtual Security_Detail Security_Detail1 { get; set; }
        public virtual ICollection<Security_Detail> Security_Detail2 { get; set; }
        public virtual ICollection<Security_Detail> Security_Detail3 { get; set; }
        public virtual ICollection<Security_Detail> Security_Detail4 { get; set; }
        public virtual ICollection<Security_Detail> Security_Detail5 { get; set; }
    }
}
