//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_Analytics
    {
        public decimal Entity_ID { get; set; }
        public decimal Security_ID { get; set; }
        public Nullable<decimal> Issued_Amount { get; set; }
        public Nullable<decimal> Market_Capitalisation { get; set; }
        public Nullable<decimal> Risk_Premium { get; set; }
        public Nullable<decimal> Exit_Price { get; set; }
        public Nullable<decimal> Total_Return_ME_1YR { get; set; }
        public Nullable<decimal> Total_Return_ME_2YR { get; set; }
        public Nullable<decimal> Total_Return_ME_3YR { get; set; }
        public Nullable<decimal> Historic_Distribution { get; set; }
        public Nullable<decimal> Distribution_Growth_Forecast_Yr1 { get; set; }
        public Nullable<decimal> Distribution_Growth_Forecast_Yr2 { get; set; }
        public Nullable<decimal> Distribution_Growth_Forecast_Yr3 { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr1 { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr2 { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr3 { get; set; }
        public Nullable<decimal> Earnings_Growth_Compounded { get; set; }
        public Nullable<decimal> Earnings_Forecast_Yr3 { get; set; }
        public Nullable<decimal> Historic_Dividend_Yield_FYE { get; set; }
        public Nullable<decimal> Forward_Dividend_Yield_FYE { get; set; }
        public Nullable<decimal> Yr3_Forward_Dividend_Yield { get; set; }
        public Nullable<decimal> Rolling_12M_Forward_Yield { get; set; }
        public Nullable<decimal> Historical_Earnings_FYE { get; set; }
        public Nullable<decimal> Earnings_Forecast_Yr1 { get; set; }
        public Nullable<decimal> Earnings_Forecast_Yr2 { get; set; }
        public Nullable<decimal> Historic_Dividend_Yield_Relative { get; set; }
        public Nullable<decimal> Rolling_12M_Historic_Distribution_PriceCurr { get; set; }
        public Nullable<decimal> Short_Term_Market_Rerate { get; set; }
        public Nullable<decimal> Forecast_12M_Total_Return { get; set; }
        public Nullable<decimal> Clean_Price { get; set; }
        public Nullable<decimal> Rolling_Dividend_Yield_Historic { get; set; }
        public System.DateTime Last_Update_Date { get; set; }
        public string Last_Update_User { get; set; }
        public Nullable<decimal> Discount_Security_ID { get; set; }
        public Nullable<decimal> Net_Present_Value { get; set; }
        public Nullable<decimal> Forecast_Rolling_Custom_Income { get; set; }
        public Nullable<decimal> Custom_Period { get; set; }
        public Nullable<decimal> Rolling_12M_Historic_Distribution { get; set; }
        public Nullable<decimal> Rolling_12M_Forecast_Distribution { get; set; }
        public Nullable<decimal> Yr2_Forward_Dividend_Yield { get; set; }
        public Nullable<decimal> Exit_Yield { get; set; }
        public Nullable<decimal> Discount_Rate { get; set; }
        public Nullable<decimal> Distribution_Growth_Compounded { get; set; }
        public Nullable<decimal> Forecast_12MRolling_Income_Accrual { get; set; }
        public Nullable<decimal> Rolling_12_to_24M_Forecast_Distribution { get; set; }
        public Nullable<decimal> Rolling_24_to_36M_Forecast_Distribution { get; set; }
        public Nullable<decimal> Forecast_Yr1_Dividend_Yield_Relative { get; set; }
        public Nullable<decimal> Market_Historic_Yield { get; set; }
        public Nullable<decimal> Market_Forward_Yield { get; set; }
        public Nullable<decimal> Historic_Distribution_PriceCurr { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr1_PriceCurr { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr2_PriceCurr { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr3_PriceCurr { get; set; }
        public Nullable<decimal> Rolling_12M_Forecast_Distribution_PriceCurr { get; set; }
        public Nullable<decimal> Rolling_12_24M_Forecast_Distribution_PriceCurr { get; set; }
        public Nullable<decimal> Rolling_24_36M_Forecast_Distribution_PriceCurr { get; set; }
        public Nullable<decimal> Distribution_Growth_Forecast_Yr4 { get; set; }
        public Nullable<decimal> Earnings_Forecast_Yr4 { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr4 { get; set; }
        public Nullable<decimal> Forecast_Distribution_Yr4_PriceCurr { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Security_Detail Security_Detail { get; set; }
        public virtual Security_Detail Security_Detail1 { get; set; }
        public virtual User User { get; set; }
    }
}
