//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_Type
    {
        public decimal Entity_ID { get; set; }
        public string Security_Type_Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Primary_Asset_Class_Code { get; set; }
        public decimal Price_Multiplier { get; set; }
        public int Decimal_Precision { get; set; }
        public int AvePrice_Rounding { get; set; }
        public string Clean_Price_Formula { get; set; }
        public string Accrued_Income_Price_Formula { get; set; }
        public Nullable<decimal> Min_Lot_Size { get; set; }
        public bool System_Locked { get; set; }
    
        public virtual Entity Entity { get; set; }
    }
}
