//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetopeMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Portfolios = new HashSet<Portfolio>();
            this.Security_Price = new HashSet<Security_Price>();
            this.Security_Price_History = new HashSet<Security_Price_History>();
            this.Security_Dividend_Detail = new HashSet<Security_Dividend_Detail>();
            this.Security_Analytics = new HashSet<Security_Analytics>();
            this.Security_Analytics_History = new HashSet<Security_Analytics_History>();
        }
    
        public decimal Entity_ID { get; set; }
        public string User_Code { get; set; }
        public string User_Name { get; set; }
        public string User_Initial { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_Address { get; set; }
        public string Active_Indicator { get; set; }
        public string Export_Folder { get; set; }
        public string User_Type { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Password_Expire_Date { get; set; }
        public string Lock_Indicator { get; set; }
        public Nullable<int> Login_Fail_Count { get; set; }
        public Nullable<System.DateTime> Login_Fail_Time { get; set; }
        public Nullable<System.DateTime> Last_Login_Time { get; set; }
        public bool System_Locked { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<Portfolio> Portfolios { get; set; }
        public virtual ICollection<Security_Price> Security_Price { get; set; }
        public virtual ICollection<Security_Price_History> Security_Price_History { get; set; }
        public virtual ICollection<Security_Dividend_Detail> Security_Dividend_Detail { get; set; }
        public virtual ICollection<Security_Analytics> Security_Analytics { get; set; }
        public virtual ICollection<Security_Analytics_History> Security_Analytics_History { get; set; }
    }
}
